fix: running storybook in different repo named dir
influxdata/giraffe pull request #498
Opened 2021-03-11 11:24 UTC by Sciator

Solves  #497

2021-03-12 22:39 UTC, TCL735 requested changes

2021-03-12 22:39 UTC, TCL735 commented on stories/.storybook/webpack.config.js
> +              rootDir: '..',
What's the difference between this and just deleting the whole line?

2021-03-12 22:39 UTC, TCL735 commented on stories/.storybook/webpack.config.js
> +              rootDir: '..',
There is a separate PR already merged for this https://github.com/influxdata/giraffe/pull/500

2021-03-19 13:37 UTC, Sciator commented
Closed by #500

2021-03-19 13:37 UTC, closed without merging