chore: clean up drift between parsers after proven success
influxdata/giraffe pull request #759
Opened 2022-06-01 17:17 UTC by asalem1

This PR consolidates the changes that were made here:

https://github.com/influxdata/giraffe/pull/752

### Background

The linked PR was made to help address some performance issues with the fromFlux parser. After merging the changes in, publishing a new version of giraffe in the UI, and feature flagging the usages of fromFlux in the UI to use the `fastFromFlux` the parser changes appear to have improved the UI's usage of the parser without any known issues. Having said that, this implementation still relies upon allocating memory for chunks of data that are then parsed, chunked and joined again. While this imperfect implementation is a lot better than the previous one, we want to be able to iterate on the `fastFromFlux` parser without compromising gains made to the parser.

### Reviewer Notes

This PR basically just updates the changes that were applied to the `fastFromFlux` parser to the `fromFlux` parser after it's been a proven success. The plan here is to publish a new version of giraffe, turn the `fastFromFlux` feature flag off in the UI with the newly published version of giraffe, and iterate on updating the `fastFromFlux` parser so that we can improve performance without compromising gains

2022-06-01 18:24 UTC, hoorayimhelping approved these changes
Have a minor suggestion on variable naming for consistency

2022-06-01 18:24 UTC, hoorayimhelping commented on giraffe/src/utils/fromFlux.ts
> +          }
It looks like this `else` block is not necessary, since `result` is defaulted to `null` on line 198.

2022-06-01 18:24 UTC, hoorayimhelping commented on giraffe/src/utils/fromFlux.ts
> +    */
Helpful, thank you :+1:

2022-06-01 18:31 UTC, hoorayimhelping requested changes
Actually, before you merge this in, would you please update the version in `giraffe/giraffe/package.json` and `giraffe/stories/package.json`?

2022-06-01 19:00 UTC, TCL735 commented
Generally, I like that the changes make the function more performant.

I am trying to fully understand all of the proposed changes that will go back into the original `fromFlux` function rather than just being its own separate function, so my review will take a bit of time to be completed. I may add comments or questions over a period of time rather than all at once.

Once I am completely done with comments and questions, I will clearly indicate so.

Thanks for your patience.

2022-06-01 19:57 UTC, asalem1 commented on giraffe/src/utils/fromFlux.ts
> +    fluxCSV = fluxCSV.trimEnd()
That's a great question. Ideally we wouldn't even want to use trimEnd. All of these operations are allocation memory to data that we already have. While this had previously been `trim`, we transitioned to using `trimEnd` while also using an index reference to find the first non-whitespace character and just start iterating from there (line 108)

2022-06-08 21:20 UTC, TCL735 approved these changes

2022-06-08 21:29 UTC, merged